# Generated by Django 6.0.4 on 2026-05-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblivros',
            name='autor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
